// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: musica.proto

package proto;

public final class Musica {
  private Musica() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface musica_protoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.musica_proto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string nome = 1;</code>
     */
    boolean hasNome();
    /**
     * <code>required string nome = 1;</code>
     */
    java.lang.String getNome();
    /**
     * <code>required string nome = 1;</code>
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>required string album = 2;</code>
     */
    boolean hasAlbum();
    /**
     * <code>required string album = 2;</code>
     */
    java.lang.String getAlbum();
    /**
     * <code>required string album = 2;</code>
     */
    com.google.protobuf.ByteString
        getAlbumBytes();

    /**
     * <code>required int32 trackNro = 3;</code>
     */
    boolean hasTrackNro();
    /**
     * <code>required int32 trackNro = 3;</code>
     */
    int getTrackNro();

    /**
     * <code>required bool onTheRadio = 4;</code>
     */
    boolean hasOnTheRadio();
    /**
     * <code>required bool onTheRadio = 4;</code>
     */
    boolean getOnTheRadio();
  }
  /**
   * Protobuf type {@code proto.musica_proto}
   */
  public  static final class musica_proto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.musica_proto)
      musica_protoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use musica_proto.newBuilder() to construct.
    private musica_proto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private musica_proto() {
      nome_ = "";
      album_ = "";
      trackNro_ = 0;
      onTheRadio_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private musica_proto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              nome_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              album_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              trackNro_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              onTheRadio_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Musica.internal_static_proto_musica_proto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Musica.internal_static_proto_musica_proto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Musica.musica_proto.class, proto.Musica.musica_proto.Builder.class);
    }

    private int bitField0_;
    public static final int NOME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nome_;
    /**
     * <code>required string nome = 1;</code>
     */
    public boolean hasNome() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string nome = 1;</code>
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nome_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nome = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALBUM_FIELD_NUMBER = 2;
    private volatile java.lang.Object album_;
    /**
     * <code>required string album = 2;</code>
     */
    public boolean hasAlbum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string album = 2;</code>
     */
    public java.lang.String getAlbum() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          album_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string album = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAlbumBytes() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        album_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRACKNRO_FIELD_NUMBER = 3;
    private int trackNro_;
    /**
     * <code>required int32 trackNro = 3;</code>
     */
    public boolean hasTrackNro() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 trackNro = 3;</code>
     */
    public int getTrackNro() {
      return trackNro_;
    }

    public static final int ONTHERADIO_FIELD_NUMBER = 4;
    private boolean onTheRadio_;
    /**
     * <code>required bool onTheRadio = 4;</code>
     */
    public boolean hasOnTheRadio() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool onTheRadio = 4;</code>
     */
    public boolean getOnTheRadio() {
      return onTheRadio_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNome()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlbum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTrackNro()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOnTheRadio()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nome_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, album_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, trackNro_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, onTheRadio_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nome_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, album_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, trackNro_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, onTheRadio_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Musica.musica_proto)) {
        return super.equals(obj);
      }
      proto.Musica.musica_proto other = (proto.Musica.musica_proto) obj;

      boolean result = true;
      result = result && (hasNome() == other.hasNome());
      if (hasNome()) {
        result = result && getNome()
            .equals(other.getNome());
      }
      result = result && (hasAlbum() == other.hasAlbum());
      if (hasAlbum()) {
        result = result && getAlbum()
            .equals(other.getAlbum());
      }
      result = result && (hasTrackNro() == other.hasTrackNro());
      if (hasTrackNro()) {
        result = result && (getTrackNro()
            == other.getTrackNro());
      }
      result = result && (hasOnTheRadio() == other.hasOnTheRadio());
      if (hasOnTheRadio()) {
        result = result && (getOnTheRadio()
            == other.getOnTheRadio());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNome()) {
        hash = (37 * hash) + NOME_FIELD_NUMBER;
        hash = (53 * hash) + getNome().hashCode();
      }
      if (hasAlbum()) {
        hash = (37 * hash) + ALBUM_FIELD_NUMBER;
        hash = (53 * hash) + getAlbum().hashCode();
      }
      if (hasTrackNro()) {
        hash = (37 * hash) + TRACKNRO_FIELD_NUMBER;
        hash = (53 * hash) + getTrackNro();
      }
      if (hasOnTheRadio()) {
        hash = (37 * hash) + ONTHERADIO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getOnTheRadio());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Musica.musica_proto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Musica.musica_proto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Musica.musica_proto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Musica.musica_proto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Musica.musica_proto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Musica.musica_proto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Musica.musica_proto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Musica.musica_proto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Musica.musica_proto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Musica.musica_proto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Musica.musica_proto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Musica.musica_proto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Musica.musica_proto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.musica_proto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.musica_proto)
        proto.Musica.musica_protoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Musica.internal_static_proto_musica_proto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Musica.internal_static_proto_musica_proto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Musica.musica_proto.class, proto.Musica.musica_proto.Builder.class);
      }

      // Construct using proto.Musica.musica_proto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nome_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        album_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        trackNro_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        onTheRadio_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Musica.internal_static_proto_musica_proto_descriptor;
      }

      @java.lang.Override
      public proto.Musica.musica_proto getDefaultInstanceForType() {
        return proto.Musica.musica_proto.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Musica.musica_proto build() {
        proto.Musica.musica_proto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Musica.musica_proto buildPartial() {
        proto.Musica.musica_proto result = new proto.Musica.musica_proto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nome_ = nome_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.album_ = album_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.trackNro_ = trackNro_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.onTheRadio_ = onTheRadio_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Musica.musica_proto) {
          return mergeFrom((proto.Musica.musica_proto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Musica.musica_proto other) {
        if (other == proto.Musica.musica_proto.getDefaultInstance()) return this;
        if (other.hasNome()) {
          bitField0_ |= 0x00000001;
          nome_ = other.nome_;
          onChanged();
        }
        if (other.hasAlbum()) {
          bitField0_ |= 0x00000002;
          album_ = other.album_;
          onChanged();
        }
        if (other.hasTrackNro()) {
          setTrackNro(other.getTrackNro());
        }
        if (other.hasOnTheRadio()) {
          setOnTheRadio(other.getOnTheRadio());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasNome()) {
          return false;
        }
        if (!hasAlbum()) {
          return false;
        }
        if (!hasTrackNro()) {
          return false;
        }
        if (!hasOnTheRadio()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Musica.musica_proto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Musica.musica_proto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object nome_ = "";
      /**
       * <code>required string nome = 1;</code>
       */
      public boolean hasNome() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string nome = 1;</code>
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nome_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nome = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nome = 1;</code>
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nome = 1;</code>
       */
      public Builder clearNome() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>required string nome = 1;</code>
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nome_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object album_ = "";
      /**
       * <code>required string album = 2;</code>
       */
      public boolean hasAlbum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string album = 2;</code>
       */
      public java.lang.String getAlbum() {
        java.lang.Object ref = album_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            album_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string album = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAlbumBytes() {
        java.lang.Object ref = album_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          album_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string album = 2;</code>
       */
      public Builder setAlbum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        album_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string album = 2;</code>
       */
      public Builder clearAlbum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        album_ = getDefaultInstance().getAlbum();
        onChanged();
        return this;
      }
      /**
       * <code>required string album = 2;</code>
       */
      public Builder setAlbumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        album_ = value;
        onChanged();
        return this;
      }

      private int trackNro_ ;
      /**
       * <code>required int32 trackNro = 3;</code>
       */
      public boolean hasTrackNro() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 trackNro = 3;</code>
       */
      public int getTrackNro() {
        return trackNro_;
      }
      /**
       * <code>required int32 trackNro = 3;</code>
       */
      public Builder setTrackNro(int value) {
        bitField0_ |= 0x00000004;
        trackNro_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 trackNro = 3;</code>
       */
      public Builder clearTrackNro() {
        bitField0_ = (bitField0_ & ~0x00000004);
        trackNro_ = 0;
        onChanged();
        return this;
      }

      private boolean onTheRadio_ ;
      /**
       * <code>required bool onTheRadio = 4;</code>
       */
      public boolean hasOnTheRadio() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool onTheRadio = 4;</code>
       */
      public boolean getOnTheRadio() {
        return onTheRadio_;
      }
      /**
       * <code>required bool onTheRadio = 4;</code>
       */
      public Builder setOnTheRadio(boolean value) {
        bitField0_ |= 0x00000008;
        onTheRadio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool onTheRadio = 4;</code>
       */
      public Builder clearOnTheRadio() {
        bitField0_ = (bitField0_ & ~0x00000008);
        onTheRadio_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.musica_proto)
    }

    // @@protoc_insertion_point(class_scope:proto.musica_proto)
    private static final proto.Musica.musica_proto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Musica.musica_proto();
    }

    public static proto.Musica.musica_proto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<musica_proto>
        PARSER = new com.google.protobuf.AbstractParser<musica_proto>() {
      @java.lang.Override
      public musica_proto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new musica_proto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<musica_proto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<musica_proto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Musica.musica_proto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_musica_proto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_musica_proto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014musica.proto\022\005proto\"Q\n\014musica_proto\022\014\n" +
      "\004nome\030\001 \002(\t\022\r\n\005album\030\002 \002(\t\022\020\n\010trackNro\030\003" +
      " \002(\005\022\022\n\nonTheRadio\030\004 \002(\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_musica_proto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_musica_proto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_musica_proto_descriptor,
        new java.lang.String[] { "Nome", "Album", "TrackNro", "OnTheRadio", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
