# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: musica.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='musica.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=_b('\n\027com.nfaustino.app.protoB\nMusicProto'),
  serialized_pb=_b('\n\x0cmusica.proto\x12\x08protobuf\"J\n\x05Music\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05\x61lbum\x18\x02 \x01(\t\x12\x10\n\x08trackNro\x18\x03 \x01(\x05\x12\x12\n\nonTheRadio\x18\x04 \x01(\x08\x42%\n\x17\x63om.nfaustino.app.protoB\nMusicProtob\x06proto3')
)




_MUSIC = _descriptor.Descriptor(
  name='Music',
  full_name='protobuf.Music',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='protobuf.Music.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='album', full_name='protobuf.Music.album', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trackNro', full_name='protobuf.Music.trackNro', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='onTheRadio', full_name='protobuf.Music.onTheRadio', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['Music'] = _MUSIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Music = _reflection.GeneratedProtocolMessageType('Music', (_message.Message,), dict(
  DESCRIPTOR = _MUSIC,
  __module__ = 'musica_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.Music)
  ))
_sym_db.RegisterMessage(Music)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
