# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: musica.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='musica.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0cmusica.proto\"K\n\x06musica\x12\x0c\n\x04nome\x18\x01 \x02(\t\x12\r\n\x05\x61lbum\x18\x02 \x02(\t\x12\x10\n\x08trackNro\x18\x03 \x02(\x05\x12\x12\n\nonTheRadio\x18\x04 \x02(\x08')
)




_MUSICA = _descriptor.Descriptor(
  name='musica',
  full_name='musica',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='musica.nome', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='album', full_name='musica.album', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trackNro', full_name='musica.trackNro', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='onTheRadio', full_name='musica.onTheRadio', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['musica'] = _MUSICA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

musica = _reflection.GeneratedProtocolMessageType('musica', (_message.Message,), dict(
  DESCRIPTOR = _MUSICA,
  __module__ = 'musica_pb2'
  # @@protoc_insertion_point(class_scope:musica)
  ))
_sym_db.RegisterMessage(musica)


# @@protoc_insertion_point(module_scope)
