// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: musica.proto

package com.nfaustino.app.proto;

public final class MusicProto {
  private MusicProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MusicOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Music)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nome = 1;</code>
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 1;</code>
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>string album = 2;</code>
     */
    java.lang.String getAlbum();
    /**
     * <code>string album = 2;</code>
     */
    com.google.protobuf.ByteString
        getAlbumBytes();

    /**
     * <code>int32 trackNro = 3;</code>
     */
    int getTrackNro();

    /**
     * <code>bool onTheRadio = 4;</code>
     */
    boolean getOnTheRadio();
  }
  /**
   * Protobuf type {@code protobuf.Music}
   */
  public  static final class Music extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Music)
      MusicOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Music.newBuilder() to construct.
    private Music(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Music() {
      nome_ = "";
      album_ = "";
      trackNro_ = 0;
      onTheRadio_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Music(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nome_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              album_ = s;
              break;
            }
            case 24: {

              trackNro_ = input.readInt32();
              break;
            }
            case 32: {

              onTheRadio_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nfaustino.app.proto.MusicProto.internal_static_protobuf_Music_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nfaustino.app.proto.MusicProto.internal_static_protobuf_Music_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nfaustino.app.proto.MusicProto.Music.class, com.nfaustino.app.proto.MusicProto.Music.Builder.class);
    }

    public static final int NOME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 1;</code>
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALBUM_FIELD_NUMBER = 2;
    private volatile java.lang.Object album_;
    /**
     * <code>string album = 2;</code>
     */
    public java.lang.String getAlbum() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        album_ = s;
        return s;
      }
    }
    /**
     * <code>string album = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAlbumBytes() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        album_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRACKNRO_FIELD_NUMBER = 3;
    private int trackNro_;
    /**
     * <code>int32 trackNro = 3;</code>
     */
    public int getTrackNro() {
      return trackNro_;
    }

    public static final int ONTHERADIO_FIELD_NUMBER = 4;
    private boolean onTheRadio_;
    /**
     * <code>bool onTheRadio = 4;</code>
     */
    public boolean getOnTheRadio() {
      return onTheRadio_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nome_);
      }
      if (!getAlbumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, album_);
      }
      if (trackNro_ != 0) {
        output.writeInt32(3, trackNro_);
      }
      if (onTheRadio_ != false) {
        output.writeBool(4, onTheRadio_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nome_);
      }
      if (!getAlbumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, album_);
      }
      if (trackNro_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, trackNro_);
      }
      if (onTheRadio_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, onTheRadio_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nfaustino.app.proto.MusicProto.Music)) {
        return super.equals(obj);
      }
      com.nfaustino.app.proto.MusicProto.Music other = (com.nfaustino.app.proto.MusicProto.Music) obj;

      boolean result = true;
      result = result && getNome()
          .equals(other.getNome());
      result = result && getAlbum()
          .equals(other.getAlbum());
      result = result && (getTrackNro()
          == other.getTrackNro());
      result = result && (getOnTheRadio()
          == other.getOnTheRadio());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + ALBUM_FIELD_NUMBER;
      hash = (53 * hash) + getAlbum().hashCode();
      hash = (37 * hash) + TRACKNRO_FIELD_NUMBER;
      hash = (53 * hash) + getTrackNro();
      hash = (37 * hash) + ONTHERADIO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOnTheRadio());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nfaustino.app.proto.MusicProto.Music parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nfaustino.app.proto.MusicProto.Music parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nfaustino.app.proto.MusicProto.Music parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nfaustino.app.proto.MusicProto.Music parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nfaustino.app.proto.MusicProto.Music parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nfaustino.app.proto.MusicProto.Music parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nfaustino.app.proto.MusicProto.Music parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nfaustino.app.proto.MusicProto.Music parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nfaustino.app.proto.MusicProto.Music parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nfaustino.app.proto.MusicProto.Music parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nfaustino.app.proto.MusicProto.Music parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nfaustino.app.proto.MusicProto.Music parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nfaustino.app.proto.MusicProto.Music prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Music}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Music)
        com.nfaustino.app.proto.MusicProto.MusicOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nfaustino.app.proto.MusicProto.internal_static_protobuf_Music_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nfaustino.app.proto.MusicProto.internal_static_protobuf_Music_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nfaustino.app.proto.MusicProto.Music.class, com.nfaustino.app.proto.MusicProto.Music.Builder.class);
      }

      // Construct using com.nfaustino.app.proto.MusicProto.Music.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nome_ = "";

        album_ = "";

        trackNro_ = 0;

        onTheRadio_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nfaustino.app.proto.MusicProto.internal_static_protobuf_Music_descriptor;
      }

      @java.lang.Override
      public com.nfaustino.app.proto.MusicProto.Music getDefaultInstanceForType() {
        return com.nfaustino.app.proto.MusicProto.Music.getDefaultInstance();
      }

      @java.lang.Override
      public com.nfaustino.app.proto.MusicProto.Music build() {
        com.nfaustino.app.proto.MusicProto.Music result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.nfaustino.app.proto.MusicProto.Music buildPartial() {
        com.nfaustino.app.proto.MusicProto.Music result = new com.nfaustino.app.proto.MusicProto.Music(this);
        result.nome_ = nome_;
        result.album_ = album_;
        result.trackNro_ = trackNro_;
        result.onTheRadio_ = onTheRadio_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nfaustino.app.proto.MusicProto.Music) {
          return mergeFrom((com.nfaustino.app.proto.MusicProto.Music)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nfaustino.app.proto.MusicProto.Music other) {
        if (other == com.nfaustino.app.proto.MusicProto.Music.getDefaultInstance()) return this;
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (!other.getAlbum().isEmpty()) {
          album_ = other.album_;
          onChanged();
        }
        if (other.getTrackNro() != 0) {
          setTrackNro(other.getTrackNro());
        }
        if (other.getOnTheRadio() != false) {
          setOnTheRadio(other.getOnTheRadio());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nfaustino.app.proto.MusicProto.Music parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nfaustino.app.proto.MusicProto.Music) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 1;</code>
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object album_ = "";
      /**
       * <code>string album = 2;</code>
       */
      public java.lang.String getAlbum() {
        java.lang.Object ref = album_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          album_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string album = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAlbumBytes() {
        java.lang.Object ref = album_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          album_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string album = 2;</code>
       */
      public Builder setAlbum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        album_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string album = 2;</code>
       */
      public Builder clearAlbum() {
        
        album_ = getDefaultInstance().getAlbum();
        onChanged();
        return this;
      }
      /**
       * <code>string album = 2;</code>
       */
      public Builder setAlbumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        album_ = value;
        onChanged();
        return this;
      }

      private int trackNro_ ;
      /**
       * <code>int32 trackNro = 3;</code>
       */
      public int getTrackNro() {
        return trackNro_;
      }
      /**
       * <code>int32 trackNro = 3;</code>
       */
      public Builder setTrackNro(int value) {
        
        trackNro_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 trackNro = 3;</code>
       */
      public Builder clearTrackNro() {
        
        trackNro_ = 0;
        onChanged();
        return this;
      }

      private boolean onTheRadio_ ;
      /**
       * <code>bool onTheRadio = 4;</code>
       */
      public boolean getOnTheRadio() {
        return onTheRadio_;
      }
      /**
       * <code>bool onTheRadio = 4;</code>
       */
      public Builder setOnTheRadio(boolean value) {
        
        onTheRadio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool onTheRadio = 4;</code>
       */
      public Builder clearOnTheRadio() {
        
        onTheRadio_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Music)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Music)
    private static final com.nfaustino.app.proto.MusicProto.Music DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nfaustino.app.proto.MusicProto.Music();
    }

    public static com.nfaustino.app.proto.MusicProto.Music getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Music>
        PARSER = new com.google.protobuf.AbstractParser<Music>() {
      @java.lang.Override
      public Music parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Music(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Music> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Music> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.nfaustino.app.proto.MusicProto.Music getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Music_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Music_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014musica.proto\022\010protobuf\"J\n\005Music\022\014\n\004nom" +
      "e\030\001 \001(\t\022\r\n\005album\030\002 \001(\t\022\020\n\010trackNro\030\003 \001(\005" +
      "\022\022\n\nonTheRadio\030\004 \001(\010B%\n\027com.nfaustino.ap" +
      "p.protoB\nMusicProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Music_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Music_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Music_descriptor,
        new java.lang.String[] { "Nome", "Album", "TrackNro", "OnTheRadio", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
